### ISSUE TITLE
[Epic] 

### ISSUE THREAD

**Issue by SherRao** [KonferCA/SPUR#177]
## Checklist
Before submitting this epic, make sure this epic:
- [ ] Is **labelled properly** - make sure to add labels for each part of the project this epic will touch.
- [ ] Has the **SPUR project assigned to it**.
- [ ] Has an **assigned milestone**.
- [ ] Has everyone that will work on it assigned. 

## Description
Replace this text with a brief description of the epic.

## Tickets
- [ ] Replace this with a list of tickets that have been made. Tickets can be referenced by typing "#" followed by the issue ID>
