### ISSUE TITLE
[Epic] Finish the admin dashboard UI

### ISSUE THREAD

**Issue by SherRao** [KonferCA/SPUR#198]
## Checklist
Before submitting this epic, make sure this epic:
- [x] Is **labelled properly** - make sure to add labels for each part of the project this epic will touch.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.
- [x] Has everyone that will work on it assigned. 

## Description
This epic contains all tickets to ensure the UI for the admin dashboard is fully completed.

## Tickets
- [ ] #
